FROM docker.io/php:8.1.17-apache

COPY ./src/ /var/www/html/

RUN apt-get upgrade && docker-php-ext-install mysqli
RUN apt-get update && apt-get install -y git

COPY ./apache-config/000-default.conf /etc/apache2/sites-enabled/000-default.conf
COPY ./apache-config/ports.conf /etc/apache2/ports.conf

EXPOSE 8080
